auto_mapper_plus:
  options:
    create_unregistered_mappings: true
    skip_constructor: true
    use_substitution: true
    property_accessor: 'AutoMapperPlus\AutoMapperPlusBundle\PropertyAccessor\DecoratedPropertyAccessor'