nelmio_api_doc:
    documentation:
        info:
            title: Zoot - Veterinarian Manager
            description: Api documentation
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/v1(?!/doc$)
    models:
        use_jms: true